version: '3'
services:
  
  nosql-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  Mtvalidation:
    build:
      dockerfile: Dockerfile
      context: ./Mtvalidation
    container_name: Mtvalidation
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/Mtvalidation/node_modules

  Mtmxconversion:
    build:
      dockerfile: Dockerfile
      context: ./Mtmxconversion
    container_name: Mtmxconversion
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/Mtmxconversion/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/customer/node_modules
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - Mtvalidation
      - Mtmxconversion
      - customer
    ports:
      - "80:80"
 